project_id = ""

[functions.http-proxy]
verify_jwt = false

[functions.web-proxy]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.chat-send]
verify_jwt = false

[functions.chat-history]
verify_jwt = false
